files:
- '**/*.md'
- '!**/node_modules/**/*.md'
- '!dialogue/idrinthFollowerDialogueGrunt.md'
- '!dialogue/idrinthFollowerDialogueOutOfBreath.md'
language: en-GB
plugins:
- spell
- indefinite-article
- repeated-words
quiet: true
dictionaries:
- _dictionaries/
