files:
- '**/*.md'
- '!**/node_modules/**/*.md'
- '!dialogue/idrinthFollowerDialogueGrunt.md'
- '!dialogue/idrinthFollowerDialogueOutOfBreath.md'
plugins:
- spell
- indefinite-article
- repeated-words
quiet: true
ignore:
- Calenith
- bloodlust
- Covir
- Flamebreaker
- Weaponbane Cuirass
- cuirass
- Bosmer's
- vampirism
- Greatblade
- Foebane
- Kodlak
- Baar Dau
- Molag Bal
- Argonian
- warcries
- hoofprints
- Warhammers
- axe
- Akaviri
- lich
- Malacath
- Thalmor's
- Idileth
- Xinerna
- Alenia
- Greatsword
- greatsword
- greatswords
- Khajiit
- Idrinth
- daedric
- daedra
- Daedra
- Thalmor
- Tamriel
- Mephala
- Trinimac
- vampiric
- Coldharbour
- Valenwood
- Cyrodiil
- Altmer
- Aldmer
- Aldmeri
- Skyrim
- Milkdrinker
- Housecat
- Elsweyr
- mer
- Helgen
- Dunmer
- Vivec
- Bosmer
- elven
- justiciar
- Idrinth's
- Milkdrinkers
- Laas
- Slen
- Haas
- Falmer
- Nord
- Whiterun
- Peryite
- lockpick
- Boethia's
- Boethia
- Dawnbreaker
- magicka
- Markath
- Summerset
- Vampiric
- Dwemer
- Altmer's
- Thalui
- Altmeri
- Thalui's
- Riften
- Windhelm
- jarl
- Stormcloak
- Ulfric
- Calineth
- Corvir
- Thornbranch
- Laemal
- Talos
- Stormcloaks
- Auri-El
