files:
- '**/*.md'
- '!**/node_modules/**/*.md'
- '!dialogue/idrinthFollowerDialogueGrunt.md'
- '!dialogue/idrinthFollowerDialogueOutOfBreath.md'
plugins:
- spell
- indefinite-article
- repeated-words
quiet: true
dictionaries:
- _dictionaries/elder-scrolls.txt
- _dictionaries/fantasy.txt
- _dictionaries/idrinth.txt
