files:
- '**/*.md'
- '!**/node_modules/**/*.md'
- '!dialogue/idrinthFollowerDialogueGrunt.md'
- '!dialogue/idrinthFollowerDialogueOutOfBreath.md'
plugins:
- spell
- indefinite-article
- repeated-words
quiet: true
ignore:
- Idrinth
- daedric
- daedra
- Daedra
- Thalmor
- Tamriel
- Mephala
- Trinimac
- vampiric
- Coldharbour
- Valenwood
- Cyrodiil
- Altmer
- Aldmer
- Aldmeri
- Skyrim
- Milkdrinker
- Housecat
- Elsweyr
- mer
- Helgen
- Dunmer
- Vivec
- Bosmer
- elven
- justiciar
- Idrinth's
- Milkdrinkers
- Laas
- Slen
- Haas
- Falmer
- Nord
- Whiterun
- Peryite
- lockpick
- Boethia's
- Boethia
- Dawnbreaker
- magicka
- Markath
- Summerset
- Vampiric
- Dwemer
